env:
  browser: true
  es2021: true
  node: true
extends:
  - standard
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-undef: off
  no-unused-vars: off
  space-before-function-paren:
    - error
    - never
  semi:
    - error
    - always
  quotes:
    - error
    - double
