name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: "game-roulette"
  CONTAINER_NAME: "game-roulette"
  ENV_FILE_PATH: "./code/game-roulette/.env"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: npm install --only=dev 

      - name: Run ESLint
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
  
  build_and_deploy:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Build and deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            docker stop $(echo $CONTAINER_NAME)
            docker rm $(echo $CONTAINER_NAME)

            docker build -t $(echo $IMAGE_NAME) .
            docker run -d --restart always --name $(echo $CONTAINER_NAME) $(echo $IMAGE_NAME)
