name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: npm install --only=dev 

      - name: Run ESLint
        uses: wearerequired/lint-action@v2
        with:
          eslint: true

      - name: Run tests
        run: npm test
  
  build_and_deploy:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Build and deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd code/game-roulette/
            docker-compose down

            git pull
            docker-compose up --build -d